### PR TITLE
Revert "Adding standard SECURITY.MD"

### PR DESCRIPTION
**Pull request by asyalove**
Reverts MicrosoftDocs/.github#3

### CODE REVIEW

**Comment by Mason4ik** [comment]
Элементарно

**Comment by Mason4ik** [comment]
https://github.com/MicrosoftDocs/.github/pull/5#issuecomment-589333288

**Comment by Alfian878787** [comment]
asyalove:revert-3-patch-1

**Review by 7atem328 — APPROVED** [review]

**Comment by 7atem328** [comment]
def fibonacci(n)
  return n if ( 0..1 ).include? n
  (fibonacci(n - 1) + fibonacci(n - 2)) #recursive calls
end

**Review by 7atem328 — APPROVED** [review]

**Comment by 7atem328** [comment]
https://github.com/Snapchat/bitmoji-kit-sample/issues/4#issue-650800941

**Comment by RazazR** [comment]
All CLA requirements met.

**Comment by RazazR** [comment]
asyalove:revert-3-patch-1

**Pull request closed without merging**
