### PR TITLE
Adding standard SECURITY.MD

### PR DESCRIPTION
**Pull request by SyntaxC4**

### CODE REVIEW

**Comment by SyntaxC4** [comment]
@jeffwilcox Can you review and merge?

**Comment by Mason4ik** [comment]
.

**Comment by Mason4ik** [comment]
https://github.com/MicrosoftDocs/.github/pull/3#issuecomment-592403640

**Comment by Mason4ik** [comment]
https://github.com/MicrosoftDocs/.github/pull/3#issuecomment-592403640

**Pull request merged**
